---
git:
  autoForwardBranches: allBranches
  autoFetch: true
  commitPrefix:
    - pattern: "^\\w+/([^_]+).*"
      replace: "$1: "
  paging:
    colorArg: always
    pager: delta
gui:
  skipDiscardChangeWarning: true
  nerdFontsVersion: "3"
  showFileIcons: false
  expandFocusedSidePanel: true
  sidePanelWidth: 0.25
  showRandomTip: false
  showCommandLog: false
  # mainPanelSplitMode: flexible
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
notARepository: quit
os:
  edit: 'nvim --server $NVIM --remote-send ''<cmd>close<CR><cmd>lua OpenFromExternal("e", {{filename}})<CR>'''
  editAtLine: 'nvim --server $NVIM --remote-send ''<cmd>close<CR><cmd>lua OpenFromExternal("e", {{filename}}, {{line}})<CR>'''
promptToReturnFromSubprocess: false
