---
os:
  edit: 'nvim --server $NVIM --remote-send ''<cmd>close<CR><cmd>lua OpenFromExternal("e", {{filename}})<CR>'''
  editAtLine: 'nvim --server $NVIM --remote-send ''<cmd>close<CR><cmd>lua OpenFromExternal("e", {{filename}}, {{line}})<CR>'''

gui:
  skipDiscardChangeWarning: true
  theme:
    selectedLineBgColor:
      - black

promptToReturnFromSubprocess: false

git:
  autoForwardBranches: allBranches
