[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["PowerShell"]
path = "snippets/PowerShell.json"

[[sources.paths]]
scope = ["asciidoc"]
path = "snippets/asciidoc.json"

[[sources.paths]]
scope = ["beancount"]
path = "snippets/beancount.json"

[[sources.paths]]
scope = ["c"]
path = "snippets/c/c.json"

[[sources.paths]]
scope = ["c"]
path = "snippets/c/cdoc.json"

[[sources.paths]]
scope = ["cmake"]
path = "snippets/cmake.json"

[[sources.paths]]
scope = ["cobol"]
path = "snippets/cobol/vscode_cobol-compound.json"

[[sources.paths]]
scope = ["cobol"]
path = "snippets/cobol/vscode_cobol.json"

[[sources.paths]]
scope = ["cobol"]
path = "snippets/cobol/vscode_cobol_dir.json"

[[sources.paths]]
scope = ["cobol"]
path = "snippets/cobol/vscode_cobol_jcl.json"

[[sources.paths]]
scope = ["cpp"]
path = "snippets/cpp/cpp.json"

[[sources.paths]]
scope = ["cpp"]
path = "snippets/cpp/cppdoc.json"

[[sources.paths]]
scope = ["csharp"]
path = "snippets/csharp/csharp.json"

[[sources.paths]]
scope = ["csharp"]
path = "snippets/csharp/csharpdoc.json"

[[sources.paths]]
scope = ["css"]
path = "snippets/css.json"

[[sources.paths]]
scope = ["dart"]
path = "snippets/dart.json"

[[sources.paths]]
scope = ["docker"]
path = "snippets/docker/docker-compose.json"

[[sources.paths]]
scope = ["docker"]
path = "snippets/docker/docker_file.json"

[[sources.paths]]
scope = ["editorconfig"]
path = "snippets/editorconfig.json"

[[sources.paths]]
scope = ["eelixir"]
path = "snippets/eelixir.json"

[[sources.paths]]
scope = ["elixir"]
path = "snippets/elixir.json"

[[sources.paths]]
scope = ["erb"]
path = "snippets/erb.json"

[[sources.paths]]
scope = ["erlang"]
path = "snippets/erlang.json"

[[sources.paths]]
scope = ["fennel"]
path = "snippets/fennel.json"

[[sources.paths]]
scope = ["fortran"]
path = "snippets/fortran.json"

[[sources.paths]]
scope = ["fsh"]
path = "snippets/fsh.json"

[[sources.paths]]
scope = ["gdscript"]
path = "snippets/gdscript.json"

[[sources.paths]]
scope = ["gitcommit"]
path = "snippets/gitcommit.json"

[[sources.paths]]
scope = ["gleam"]
path = "snippets/gleam.json"

[[sources.paths]]
scope = ["global"]
path = "snippets/global.json"

[[sources.paths]]
scope = ["glsl"]
path = "snippets/glsl.json"

[[sources.paths]]
scope = ["go"]
path = "snippets/go.json"

[[sources.paths]]
scope = ["haskell"]
path = "snippets/haskell.json"

[[sources.paths]]
scope = ["html"]
path = "snippets/html.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/java-tests.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/java.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/javadoc.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/javascript.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/jsdoc.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/next-ts.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/next.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/react-es7.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/react-native-ts.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/react-native.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/react-ts.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/react.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/tsdoc.json"

[[sources.paths]]
scope = ["javascript"]
path = "snippets/javascript/typescript.json"

[[sources.paths]]
scope = ["julia"]
path = "snippets/julia.json"

[[sources.paths]]
scope = ["kivy"]
path = "snippets/kivy.json"

[[sources.paths]]
scope = ["kotlin"]
path = "snippets/kotlin/kdoc.json"

[[sources.paths]]
scope = ["kotlin"]
path = "snippets/kotlin/kotlin.json"

[[sources.paths]]
scope = ["kubernetes"]
path = "snippets/kubernetes.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/bibtex.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/latex-snippets.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/vscode-latex-snippets.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex.json"

[[sources.paths]]
scope = ["license"]
path = "snippets/license.json"

[[sources.paths]]
scope = ["liquid"]
path = "snippets/liquid.json"

[[sources.paths]]
scope = ["loremipsum"]
path = "snippets/loremipsum.json"

[[sources.paths]]
scope = ["lua"]
path = "snippets/lua/lua.json"

[[sources.paths]]
scope = ["lua"]
path = "snippets/lua/luadoc.json"

[[sources.paths]]
scope = ["make"]
path = "snippets/make.json"

[[sources.paths]]
scope = ["markdown"]
path = "snippets/markdown.json"

[[sources.paths]]
scope = ["mint"]
path = "snippets/mint.json"

[[sources.paths]]
scope = ["nix"]
path = "snippets/nix.json"

[[sources.paths]]
scope = ["norg"]
path = "snippets/norg.json"

[[sources.paths]]
scope = ["nushell"]
path = "snippets/nushell.json"

[[sources.paths]]
scope = ["objc"]
path = "snippets/objc.json"

[[sources.paths]]
scope = ["ocaml"]
path = "snippets/ocaml/dune-project.json"

[[sources.paths]]
scope = ["ocaml"]
path = "snippets/ocaml/dune.json"

[[sources.paths]]
scope = ["ocaml"]
path = "snippets/ocaml/ocaml.json"

[[sources.paths]]
scope = ["ocaml"]
path = "snippets/ocaml/ocamllex.json"

[[sources.paths]]
scope = ["org"]
path = "snippets/org.json"

[[sources.paths]]
scope = ["perl"]
path = "snippets/perl.json"

[[sources.paths]]
scope = ["php"]
path = "snippets/php/php.json"

[[sources.paths]]
scope = ["php"]
path = "snippets/php/phpdoc.json"

[[sources.paths]]
scope = ["plantuml"]
path = "snippets/plantuml.json"

[[sources.paths]]
scope = ["purescript"]
path = "snippets/purescript.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/comprehension.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/debug.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/pydoc.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/python.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/unittest.json"

[[sources.paths]]
scope = ["quarto"]
path = "snippets/quarto.json"

[[sources.paths]]
scope = ["r"]
path = "snippets/r.json"

[[sources.paths]]
scope = ["reason"]
path = "snippets/reason.json"

[[sources.paths]]
scope = ["rescript"]
path = "snippets/rescript.json"

[[sources.paths]]
scope = ["rmarkdown"]
path = "snippets/rmarkdown.json"

[[sources.paths]]
scope = ["rst"]
path = "snippets/rst.json"

[[sources.paths]]
scope = ["ruby"]
path = "snippets/ruby/rdoc.json"

[[sources.paths]]
scope = ["ruby"]
path = "snippets/ruby/rspec.json"

[[sources.paths]]
scope = ["ruby"]
path = "snippets/ruby/ruby.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rustdoc.json"

[[sources.paths]]
scope = ["scala"]
path = "snippets/scala.json"

[[sources.paths]]
scope = ["shell"]
path = "snippets/shell/shell.json"

[[sources.paths]]
scope = ["shell"]
path = "snippets/shell/shelldoc.json"

[[sources.paths]]
scope = ["solidity"]
path = "snippets/solidity.json"

[[sources.paths]]
scope = ["sql"]
path = "snippets/sql.json"

[[sources.paths]]
scope = ["svelte"]
path = "snippets/svelte.json"

[[sources.paths]]
scope = ["swift"]
path = "snippets/swift.json"

[[sources.paths]]
scope = ["systemverilog"]
path = "snippets/systemverilog.json"

[[sources.paths]]
scope = ["tcl"]
path = "snippets/tcl.json"

[[sources.paths]]
scope = ["terraform"]
path = "snippets/terraform.json"

[[sources.paths]]
scope = ["verilog"]
path = "snippets/verilog.json"

[[sources.paths]]
scope = ["vhdl"]
path = "snippets/vhdl.json"

[[sources.paths]]
scope = ["zig"]
path = "snippets/zig.json"

[[sources.paths]]
scope = ["angular"]
path = "snippets/frameworks/angular/html.json"

[[sources.paths]]
scope = ["angular"]
path = "snippets/frameworks/angular/jsonc.json"

[[sources.paths]]
scope = ["angular"]
path = "snippets/frameworks/angular/typescript.json"

[[sources.paths]]
scope = ["blade"]
path = "snippets/frameworks/blade/blade.json"

[[sources.paths]]
scope = ["blade"]
path = "snippets/frameworks/blade/helpers.json"

[[sources.paths]]
scope = ["blade"]
path = "snippets/frameworks/blade/livewire.json"

[[sources.paths]]
scope = ["blade"]
path = "snippets/frameworks/blade/snippets.json"

[[sources.paths]]
scope = ["django"]
path = "snippets/frameworks/django/admin.json"

[[sources.paths]]
scope = ["django"]
path = "snippets/frameworks/django/django_rest"

[[sources.paths]]
scope = ["django"]
path = "snippets/frameworks/django/forms.json"

[[sources.paths]]
scope = ["django"]
path = "snippets/frameworks/django/models.json"

[[sources.paths]]
scope = ["django"]
path = "snippets/frameworks/django/tags.json"

[[sources.paths]]
scope = ["django"]
path = "snippets/frameworks/django/urls.json"

[[sources.paths]]
scope = ["django"]
path = "snippets/frameworks/django/views.json"

[[sources.paths]]
scope = ["djangohtml"]
path = "snippets/frameworks/djangohtml.json"

[[sources.paths]]
scope = ["edge"]
path = "snippets/frameworks/edge.json"

[[sources.paths]]
scope = ["ejs"]
path = "snippets/frameworks/ejs.json"

[[sources.paths]]
scope = ["flutter"]
path = "snippets/frameworks/flutter.json"

[[sources.paths]]
scope = ["jekyll"]
path = "snippets/frameworks/jekyll.json"

[[sources.paths]]
scope = ["rails"]
path = "snippets/frameworks/rails.json"

[[sources.paths]]
scope = ["relm4"]
path = "snippets/frameworks/relm4/components.json"

[[sources.paths]]
scope = ["relm4"]
path = "snippets/frameworks/relm4/factories.json"

[[sources.paths]]
scope = ["relm4"]
path = "snippets/frameworks/relm4/templates.json"

[[sources.paths]]
scope = ["relm4"]
path = "snippets/frameworks/relm4/workers.json"

[[sources.paths]]
scope = ["remix-ts"]
path = "snippets/frameworks/remix-ts.json"

[[sources.paths]]
scope = ["twig"]
path = "snippets/frameworks/twig.json"

[[sources.paths]]
scope = ["unity"]
path = "snippets/frameworks/unity.json"

[[sources.paths]]
scope = ["unreal"]
path = "snippets/frameworks/unreal.json"

[[sources.paths]]
scope = ["vue"]
path = "snippets/frameworks/vue/html.json"

[[sources.paths]]
scope = ["vue"]
path = "snippets/frameworks/vue/nuxt-html.json"

[[sources.paths]]
scope = ["vue"]
path = "snippets/frameworks/vue/nuxt-script.json"

[[sources.paths]]
scope = ["vue"]
path = "snippets/frameworks/vue/script.json"

[[sources.paths]]
scope = ["vue"]
path = "snippets/frameworks/vue/style.json"

[[sources.paths]]
scope = ["vue"]
path = "snippets/frameworks/vue/vue.json"
