# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = "v"
run = '''shell --orphan -- nvim --server "$NVIM" --remote-send "<cmd>close<CR><cmd>lua OpenFromExternal(\"vsplit\", '$0')<CR>"'''
desc = "Open in vertical split"

[[mgr.prepend_keymap]]
on = "s"
run = '''shell --orphan -- nvim --server "$NVIM" --remote-send "<cmd>close<CR><cmd>lua OpenFromExternal(\"split\", '$0')<CR>"'''
desc = "Open in horizontal split"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = '''shell --orphan -- nvim --server "$NVIM" --remote-send "<cmd>close<CR><cmd>lua EditMultiFromYazi(\"$*\")<CR>"'''
desc = "Open selected or hovered in Neovim"
