vim.o.clipboard = "unnamedplus" -- use system clipboard
vim.o.cmdheight = 0
vim.o.confirm = true
vim.o.cursorline = true
vim.o.expandtab = true -- convert tabs to spaces
vim.o.lazyredraw = true -- fix ghostty mouse lags in nvim
vim.o.mouse = "a" -- enable mouse in all modes
vim.o.mousemoveevent = true -- enable mouse move events
vim.o.number = true
vim.o.relativenumber = true
vim.o.sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
vim.o.shiftwidth = 2 -- number of spaces used for each step of (auto)indent
vim.o.signcolumn = "yes"
vim.o.softtabstop = 2 -- number of spaces a <Tab> inserts in insert mode
vim.o.swapfile = false
vim.o.tabstop = 2 -- number of spaces that a <Tab> counts for
vim.o.timeout = true
-- vim.o.timeoutlen = 500 -- reduce timeout during keypresses
vim.o.undofile = true
vim.o.winborder = "rounded"
vim.opt.completeopt = { "menuone", "noselect", "popup" }
vim.opt.termguicolors = true
